version: "3.9"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    container_name: 3g3-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200 >/dev/null || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 20
    # networks:
    #   - webnet

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.12.2
    container_name: 3g3-filebeat
    user: root
    depends_on:
      elasticsearch:
        condition: service_healthy
    volumes:
      - ./backend/logs:/var/log/backend
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
    command: ["--strict.perms=false"]
    # networks:
    #   - webnet

  backend:
    build: ./backend
    container_name: 3g3-backend
    env_file: ./backend/.env.prod
    expose:
      - "5000"        # container iÃ§i
    networks:
      - webnet
    volumes:
      - ./backend/logs:/var/log/backend

  frontend:
    build: 
      context: ./frontend
      args:
        REACT_APP_BACKEND_URL: "https://elugemna.store/api"
    container_name: 3g3-frontend
    env_file: ./frontend/.env.prod
    expose:
      - "80"
    depends_on:
      - backend
    networks:
      - webnet

  nginx:
    image: nginx:latest
    container_name: 3g3-nginx
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./infra/conf.d:/etc/nginx/conf.d:ro
      - ./infra/certs:/etc/nginx/certs
      - /var/www/certbot:/var/www/certbot
    networks:
      - webnet

volumes:
  esdata:

networks:
  webnet:
    driver: bridge



#--------------------------------------------------------------------
# version: "3.9"

# services:
#   elasticsearch:
#     image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
#     container_name: 3g3-elasticsearch
#     environment:
#       - discovery.type=single-node
#       - xpack.security.enabled=false
#       - ES_JAVA_OPTS=-Xms512m -Xmx512m
#     ports:
#       - "9200:9200"
#     volumes:
#       - esdata:/usr/share/elasticsearch/data
#     healthcheck:
#       test: ["CMD-SHELL", "curl -s http://localhost:9200 >/dev/null || exit 1"]
#       interval: 10s
#       timeout: 5s
#       retries: 20

#   filebeat:
#     image: docker.elastic.co/beats/filebeat:8.12.2
#     container_name: 3g3-filebeat
#     user: root
#     depends_on:
#       elasticsearch:
#         condition: service_healthy
#     volumes:
#       - ./backend/logs:/var/log/backend
#       - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
#     command: ["--strict.perms=false"]

#   backend:
#     build: ./backend
#     container_name: 3g3-backend
#     env_file: ./backend/.env.prod
#     expose:
#       - "5000"
#     volumes:
#       - ./backend/logs:/var/log/backend

#   frontend:
#     build: ./frontend
#     container_name: 3g3-frontend
#     env_file: ./frontend/.env.prod
#     expose:
#       - "80"
#     depends_on:
#       - backend

#   nginx:
#     image: nginx:latest
#     container_name: 3g3-nginx
#     depends_on:
#       - frontend
#       - backend
#     ports:
#       - "80:80"
#       - "443:443"
#     volumes:
#     - ./infra/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
#     - ./infra/certs:/etc/nginx/certs
#     - /var/www/certbot:/var/www/certbot
#     # volumes:
#     #   - ./infra/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
#     #   - ./infra/certs:/etc/letsencrypt/live:rw
#       # - ./infra/certs:/etc/nginx/certs:ro
# volumes:
#   esdata: